 #
#  Makefile compiling server source
 #

BUILDHEADER	:=	server

BUILDTYPE	:=	$(BUILDTYPE_PLTLIB)

TARGET_SOURCE_DIR	:=	.	\

.PHONY: all

all:	hostbuilder

include $(MKHELPER_DIR)/builder/builder_host.mk